# Generated by Django 4.1 on 2022-10-29 19:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("discount", models.FloatField()),
                ("used", models.BooleanField(default=False)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(default=payments.models.gen_id2, max_length=200),
                ),
                ("service", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=200)),
                ("qty", models.IntegerField(default=0)),
                ("user", models.IntegerField()),
                ("date_added", models.DateTimeField(default=datetime.date.today)),
                ("link", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="VIPCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("discount", models.FloatField()),
                ("used", models.BooleanField(default=False)),
                ("date_added", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ("date_added",),
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_thumb",
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="rate",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="invoice",
            name="settled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="minimumQty",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="product",
            name="volume",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.CharField(default=payments.models.gen_id, max_length=50),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (-1, "Not Started"),
                            (0, "Unconfirmed"),
                            (1, "Partially Confirmed"),
                            (2, "Confirmed"),
                        ],
                        default=-1,
                    ),
                ),
                ("order_id", models.CharField(max_length=250)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("btcvalue", models.FloatField(blank=True, null=True)),
                ("received", models.FloatField(blank=True, null=True)),
                ("txid", models.CharField(blank=True, max_length=250, null=True)),
                ("rbf", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateField(default=datetime.date.today)),
                ("rate", models.FloatField(blank=True, default=0)),
                ("settled", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(default=payments.models.gen_id, max_length=100),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("settled", models.BooleanField(default=False)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.coupon",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="payments.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
