# Generated by Django 4.1 on 2022-11-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_coupon_serviceorder_vipcoupon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="source",
            field=models.IntegerField(default=0),
        ),
    ]
