# Generated by Django 4.1 on 2022-10-29 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="id",
        ),
        migrations.AddField(
            model_name="myuser",
            name="balance",
            field=models.FloatField(default=float),
        ),
        migrations.AddField(
            model_name="myuser",
            name="banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="myuser",
            name="date_added",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="myuser",
            name="discount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="myuser",
            name="fname",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="myuser",
            name="status",
            field=models.CharField(
                choices=[("regular", "Regular"), ("vip", "VIP")],
                default="regular",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="myuser",
            name="telegram_id",
            field=models.CharField(
                default="1000",
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="user id (telegram)",
            ),
        ),
        migrations.AddField(
            model_name="myuser",
            name="username",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
